version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo "Installing Maven..."
      - mvn -version
  build:
    commands:
      - echo "Building Lambda function..."
      - mvn clean package
      - sam package 
        --template-file template.yaml 
        --s3-bucket kjbuild 
        --output-template-file packaged-template.yaml
artifacts:
  files:
    - packaged-template.yaml