version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo "Installing Maven..."
      - mvn -version
  build:
    commands:
      - echo "Building Lambda function..."
      - mvn clean package
artifacts:
  files:
    - target/LambdaJavaAPI.jar
