version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo "Installing Maven..."
      - mvn -version
  build:
    commands:
      - echo "Building Lambda function..."
      - mvn clean package
artifacts:
  files:
    - target/LambdaJavaAPI.jar
    - template.yaml
post_build:
  commands:
    - aws s3 cp target/LambdaJavaAPI.jar s3://kjbuild
