AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: My Lambda Function

Resources:
  LambdaJavaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.api.LambdaJavaAPI
      Runtime: java11
      Code:
        S3Bucket: kjbuild
        S3Key: LambdaJavaAPI.jar
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: GET
